### PR TITLE
OwO-ify da code

### PR DESCRIPTION
**Pull request by SystematicError**
Self explanatory

### CODE REVIEW

**Comment by pratheek78** [comment]
time to add this to the actual bot as well...

**Comment by FadTheChad** [comment]
Hehehehehehehhehehe

**Comment by tonyG433** [comment]
The forbidden pr

**Comment by pratheek78** [comment]
*forks the repo(even though idk how tf a db works)*

**Comment by FadTheChad** [comment]
Fork mine :creepyGrin:

**Comment by pratheek78** [comment]
sussy baka

**Comment by FadTheChad** [comment]
kekw

**Comment by tonyG433** [comment]
> Fork mine :creepyGrin:

I'll fork your mom

**Comment by FadTheChad** [comment]
> > Fork mine :creepyGrin:
> 
> I'll fork your mom 

FadBot is my mom yes

**Comment by pratheek78** [comment]
what the actual fuck...

**Pull request closed without merging**
